// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	usecase "wallet/internal/usecase"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, walletID
func (_m *WalletRepository) GetBalance(ctx context.Context, walletID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalanceForUpdate provides a mock function with given fields: ctx, walletID
func (_m *WalletRepository) GetBalanceForUpdate(ctx context.Context, walletID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceForUpdate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOperation provides a mock function with given fields: ctx, op
func (_m *WalletRepository) SaveOperation(ctx context.Context, op usecase.Operation) error {
	ret := _m.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for SaveOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.Operation) error); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBalance provides a mock function with given fields: ctx, walletID, newBalance
func (_m *WalletRepository) UpdateBalance(ctx context.Context, walletID uuid.UUID, newBalance int64) error {
	ret := _m.Called(ctx, walletID, newBalance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = rf(ctx, walletID, newBalance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
