// Package error ...
package walleterror

import "errors"

var (
	// ErrInsufficientFunds ...
	ErrInsufficientFunds = errors.New("insufficient funds")
	// ErrWalletNotFound ...
	ErrWalletNotFound = errors.New("wallet not found")
	// ErrInvalidOperationType ...
	ErrInvalidOperationType = errors.New("invalid operation type")
	// ErrTypeNotSpecified ...
	ErrTypeNotSpecified = errors.New("type not specified")
	// ErrInvalidAmount ...
	ErrInvalidAmount = errors.New("invalid amount")
	// ErrInvalidValletID ...
	ErrInvalidValletID = errors.New("invalid wallet id")
)
